options:
  max_Log_size:
    type: int
    default: 6
    description: |
      The maximum size in MB of the audit log file. Once the log reaches the
      maximum size, it will be rotated and a new log file will be started.
      It is important that an appropriate size is determined for log files so
      that they do not impact the system and audit data is not lost.
